apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-stillingssok
    namespace: arbeidsgiver
    labels:
        team: arbeidsgiver
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - {{ ingress }}
        - {{ ingress-naisdevice }}
    liveness:
        initialDelay: 5
        path: /rekrutteringsbistand-stillingssok/internal/isAlive
    readiness:
        initialDelay: 5
        path: /rekrutteringsbistand-stillingssok/internal/isReady
    webproxy: true
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: STILLINGSOK_PROXY_URL
          value: {{ stillingssok-proxy-url }}
        - name: STILLING_API_URL
          value: {{ stilling-api-url }}
