apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-stillingssok
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - {{ ingress }}
    liveness:
        initialDelay: 5
        path: /rekrutteringsbistand-stillingssok/internal/isAlive
    readiness:
        initialDelay: 5
        path: /rekrutteringsbistand-stillingssok/internal/isReady
    azure:
      application:
        enabled: true
      sidecar:
        enabled: true
    env:
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/ca-bundle.pem
        - name: STILLINGSOK_PROXY_URL
          value: {{ stillingssok-proxy-url }}
        - name: STILLING_API_URL
          value: {{ stilling-api-url }}
