apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: rekrutteringsbistand-stillingssok
    namespace: toi
    labels:
        team: toi
spec:
    # prettier-ignore
    image: {{ image }}
    port: 3000
    ingresses:
        - {{ ingress }}
    liveness:
        initialDelay: 5
        path: /rekrutteringsbistand-stillingssok/internal/isAlive
    readiness:
        initialDelay: 5
        path: /rekrutteringsbistand-stillingssok/internal/isReady
