import { Respons } from '../../elasticSearchTyper';
import { Ansettelsesform, Omfang, Søknadsfrist } from '../../Stilling';

export const resultat: Respons = {
    took: 5,
    timed_out: false,
    _shards: { total: 3, successful: 3, skipped: 0, failed: 0 },
    hits: {
        max_score: 1.0,
        hits: [
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: 'b7f2e4ef-7d1a-45b9-b286-889de658f128',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Ordrebehandler - teknisk innesalg - sentralbord',
                        uuid: 'b7f2e4ef-7d1a-45b9-b286-889de658f128',
                        annonsenr: '123456',
                        status: 'STOPPED',
                        privacy: 'INTERNAL_NOT_SHOWN',
                        published: '2020-01-04T07:04:28.718064',
                        expires: '2020-02-14T09:57:00',
                        created: '2020-01-04T07:07:50.292658',
                        updated: '2020-01-10T07:08:26.236421',
                        employer: {
                            name: 'NORSECRAFT TEC AS',
                            publicName: 'NORSECRAFT TEC AS',
                            orgnr: '997833007',
                            parentOrgnr: '997818997',
                            orgform: 'BEDR',
                        },
                        categories: [{ styrkCode: '4110.23', name: 'Ordremedarbeider' }],
                        source: 'DIR',
                        medium: 'DIR',
                        businessName: 'Norsecraft Tec AS',
                        locations: [
                            {
                                address: 'Skuiveien 43',
                                postalCode: '1339',
                                county: 'VIKEN',
                                municipal: 'BÆRUM',
                                latitue: '59.904693603515625',
                                longitude: '10.486381530761719',
                            },
                        ],
                        reference: '137052618',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'https://www.finn.no/137052618',
                            classification_styrk08_score: 0.084096126,
                            address: 'Skuiveien 43,1339 Vøyenenga',
                            jobtitle: 'Ordrebehandler - teknisk innesalg - sentralbord',
                            author: 'Privat',
                            keywords: 'kundeservice og support,ordrebehandler,sentralbord',
                            engagementtype: Ansettelsesform.Fast,
                            classification_input_source: 'jobtitle',
                            employerdescription:
                                '<p>Norsecraft Tec AS er Norges ledende aktør innen Sentralsmøring, Blanding og Doseringssystem og Oil Cleaning Systems til norsk industri. Vi er i dag 18 ansatte fordelt på salg, teknisk (service &amp; montasje), lager/logistikk og administrasjon/økonomi.</p>\n<p>Vårt hovedkontor er på Vøyenenga i Bærum kommune.</p>\n<p>Fra starten i 1980 har Norsecraft TEC AS fokusert sterkt på utvikling av egne løsninger med basis i våre agenturer.</p>\n<p>Våre hovedleverandører er:</p>\n<p>SKF LINCOLN - Sentralsmøring<br />\nDOPAG - Blanding og Doseringssystem<br />\nEUROPAFILTER - Oil Cleaning systems.</p>\n<p>Vår styrke har hele tiden vært nøkkelferdige, kundetilpassede kvalitetssystemer</p>\n<p>Vi opplever at våre produkter og tjenester er etterspurt innenfor all type industri, både landbasert og offshore.</p>\n<p>Selskapet er i dag inndelt i to markedsområder : vei &amp; anlegg og offshore &amp; industri.</p>\n',
                            sector: 'Privat',
                            sourceupdated: '2020-01-03T09:57:00.000Z',
                            applicationurl:
                                'https://www.finn.no/recruitment/hired/frontend/applynow/input.action?adId=137052618',
                            applicationdue: Søknadsfrist.Snarest,
                            extent: Omfang.Heltid,
                            occupation: 'Kontor og administrasjon;Kundeservice;Teknisk service',
                            applicationemail: 'oek@norsecraft.no',
                            externalref: 137052618,
                            employerhomepage: 'https://www.norsecrafttec.no/',
                            searchtags: [
                                { label: 'Ordrebehandler', score: 0.077229604 },
                                { label: 'Callsentermedarbeider', score: 0.03935847 },
                                { label: 'Ordremedarbeider', score: 0.03359184 },
                                { label: 'Fulfillment Center Employee', score: 0.03359184 },
                                { label: 'Callsentermedarbeider tospråklig', score: 0.02687023 },
                            ],
                            employer: 'Norsecraft Tec AS',
                            industry: 'Annet',
                            adtext:
                                '<p>Vi søker en engasjert og serviceinnstilt medarbeider.</p>\n<p>Du vil primært jobbe med ordremottak, ordreregistrering og håndtere vårt sentralbord. Stillingen medfører kontakt med våre kunder og du må trives med å ha mange baller i luften. Du vil jobbe tett med øvrige avdelinger og vi ser for oss at du kan være en pådriver til med å utvikle oss videre. Mulighetene for et større ansvar på sikt er helt klart til stede og bør være et felles mål.</p>\n<p>Føler du at dette kan være noe for deg så syntes vi du skal søke :-)</p>\n<p><strong>Arbeidsoppgaver</strong></p>\n<ul><li>Registrering og oppfølging av ordre og leveranser</li><li>Sentralbord</li><li>Kunde- og selgerstøtte</li><li>Telefonisk salg ved kundehenvendelser</li><li>Ansvar for CRM utviklingen i selskapet</li><li>Ansvar for våre internettsider</li><li>Oppfølging av våre salg og montasjepartnere</li></ul>\n<p><strong>Kvalifikasjoner</strong></p>\n<ul><li>Relevant erfaring innen kundebehandling, logistikk og ordrebehandling</li><li>Systematisk og pliktoppfyllende</li><li>Erfaring med CRM og økonomisystemer</li><li>Generelt gode IT kunnskaper</li><li>Økonomisk forståelse</li><li>Erfaring fra anlegg / industri bransjen er en fordel</li></ul>\n<p><strong>Personlige egenskaper</strong></p>\n<ul><li>Serviceminded</li><li>Gode samarbeidsevner</li><li>Tydelig og bestemt</li><li>Nøyaktig og evner å håndtere høyt arbeidstempo</li><li>God formuleringsevne, skriftlig og muntlig</li></ul>\n<p><strong>Språkkunnskaper</strong></p>\n<ul><li>flytende norsk, skriftlig og muntlig</li><li>beherske engelsk, skriftlig og muntlig</li></ul>\n',
                            location: 'Vøyenenga',
                        },
                    },
                    stillingsinfo: {
                        eierNavident: 'E137876',
                        eierNavn: 'Vetlesen, Veileder',
                        notat: 'Dette er en stilling som bør passe for de fleste blide mennesker',
                        stillingsid: 'aa8e80a1-1d09-42af-b50f-10dd0c176e9e',
                        stillingsinfoid: 'ea4a791a-59e5-4fad-9fc2-ee3508f07842',
                    },
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: '82a23984-e5fa-4cb6-b711-d4bedb91c885',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Snart gjennomført førstegangstjenesten og klar for jobb?',
                        uuid: '82a23984-e5fa-4cb6-b711-d4bedb91c885',
                        annonsenr: '123456',
                        status: 'STOPPED',
                        privacy: 'SHOW_ALL',
                        published: '2020-01-07T07:05:18.243009',
                        expires: '2020-02-17T22:59:00',
                        created: '2020-01-07T07:10:16.96851',
                        updated: '2020-01-10T07:08:26.497387',
                        employer: {
                            name: 'DREAMWORK TALENTS AS',
                            publicName: 'DREAMWORK TALENTS AS',
                            orgnr: '912407705',
                            parentOrgnr: '912384152',
                            orgform: 'BEDR',
                        },
                        categories: [],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'Dreamwork Talents AS',
                        locations: [
                            {
                                address: 'Gjerdums Vei 11,',
                                postalCode: '0484',
                                county: 'OSLO',
                                municipal: 'OSLO',
                                latitue: '59.9484977722168',
                                longitude: '10.767707824707031',
                            },
                        ],
                        reference: '167002158',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'https://www.finn.no/167002158',
                            address: 'Gjerdums Vei 11,,0484 Oslo',
                            positioncount: 5,
                            jobtitle: 'Medarbeider',
                            author: 'Dreamwork',
                            keywords:
                                'Kundebehandling,Salg,B2B,B2C,Kundeservice,Møtebooking,Konsulent',
                            engagementtype: Ansettelsesform.Engasjement,
                            classification_input_source: 'jobtitle',
                            employerdescription:
                                '<p>Hos oss i Dreamwork jobber vi med rekruttering og bemanning, og leverer tjenester til både privat og offentlig sektor innenfor en rekke ulike fagområder. Vi er opptatt av at du som kandidat finner drømmejobben og at du som kunde finner drømmekandidaten, vi kaller det profesjonell matchmaking .</p>\n<p>Vi vet at det å skape tillit og lytte til deg, enten du er kunde eller kandidat, er avgjørende for å ansette rett person til rett stilling.</p>\n<p>Vårt team består av dyktige rådgivere som alltid er tilgjengelig for både kunder og kandidater, og som er eksperter på sine fagområder.</p>\n<p>Dreamwork - What is your dream?</p>\n',
                            sector: 'Privat',
                            sourceupdated: '2020-01-06T08:07:00.000Z',
                            applicationurl:
                                'https://apply.recman.no/job_post.php?id=116038&path=finn',
                            applicationdue: Søknadsfrist.Snarest,
                            extent: Omfang.Heltid,
                            logomain:
                                'https://images.finncdn.no/mmo/logo/object/4329380/iad_4325937945259165194dw_logo_rgb_bruk.png',
                            externalref: 116038,
                            logolisting:
                                'https://images.finncdn.no/mmo/logo/result/4329380/iad_5147928685022827379dw_logo_rgb_bruk.png',
                            employerhomepage: 'http://www.dreamwork.no',
                            starttime: 'Snarest',
                            searchtags: [
                                {
                                    label: 'Lagermedarbeider med trucksertifikat',
                                    score: 0.62219125,
                                },
                                { label: 'Medarbeider høylager', score: 0.6221755 },
                                { label: 'Renseriarbeider', score: 0.6186539 },
                                { label: 'Blomsterselger', score: 0.610135 },
                            ],
                            employer: 'Dreamwork Talents AS',
                            industry: 'Konsulent og rådgivning',
                            adtext:
                                '<p><strong>I disse dager skal mange unge og lovende dimme etter endt førstegangstjeneste.</strong></p>\n<p>Vi i Dreamwork vet at erfaringen og læringen man får i forsvaret er helt unik! Mange opparbeider en disiplin, utholdenhet og evne til lagarbeid som vil være utrolig verdifull i arbeidslivet. Derfor ønsker vi å komme i kontakt med deg som snart eller nylig har gjennomført førstegangstjenesten og er klar for nye utfordringer! Du må være bosatt eller ha planer om å bosette deg i Oslo/Akershus.</p>\n<p>Kanskje drømmer du om en karriere i næringslivet eller ønsker deg en kontorhverdag. Vi har mange spennende prosjekter innen kundebehandling, salg og møtebooking som trenger folk som nettopp deg!</p>\n<p>Vi ønsker å være din sparringspartner i arbeidslivet og kan bistå med karriereplanlegging, slik at du får den rette utviklingen på veg mot drømmejobben!</p>\n<p><strong>Vi tilbyr</strong></p>\n<ul><li>\n<p>Rådgivning der vi sammen legger opp en karriereplan for å nå din drømmejobb</p>\n</li><li>\n<p>God oppfølging og veiledning av våre rådgivere gjennom hele karrieren</p>\n</li><li>\n<p>Samarbeidspartnere med fast timelønn og gode bonusordninger</p>\n</li><li>\n<p>Utvikling/kurs-program som sikrer at du får rett kompetanse for din karriere</p>\n</li><li>\n<p>Stabile og trygge arbeidsplasser</p>\n</li></ul>\n<p>Dersom du kjenner deg igjen, ønsker vi en prat med deg! Registrer CV/søknad ved å trykke på knappen &lt;&lt;søk her&gt;&gt;</p>\n',
                            location: 'Oslo',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: 'ac6d7a0d-6715-4f00-9da1-c9af608ac977',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'KIWI Råbekken søker etter butikksjef',
                        uuid: 'ac6d7a0d-6715-4f00-9da1-c9af608ac977',
                        annonsenr: '123456',
                        status: 'INACTIVE',
                        privacy: 'SHOW_ALL',
                        published: '2019-12-12T07:03:48.487786',
                        expires: '2020-01-11T00:00:00',
                        created: '2019-12-12T07:06:12.328378',
                        updated: '2020-01-11T01:31:19.493987',
                        employer: {
                            name: 'KIWI RÅBEKKEN',
                            publicName: 'KIWI RÅBEKKEN',
                            orgnr: '971633786',
                            parentOrgnr: '877227162',
                            orgform: 'BEDR',
                        },
                        categories: [{ styrkCode: '1420.07', name: 'Daglig leder (butikk)' }],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'KIWI Råbekken',
                        locations: [
                            {
                                address: 'Dikeveien 6',
                                postalCode: '1661',
                                county: 'VIKEN',
                                municipal: 'FREDRIKSTAD',
                                latitue: '59.24449920654297',
                                longitude: '10.98370361328125',
                            },
                        ],
                        reference: '165340613',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'https://www.finn.no/165340613',
                            classification_styrk08_score: 0.93524605,
                            address: 'Dikeveien 6,1661 Rolvsøy',
                            jobtitle: 'Butikkleder',
                            author: 'Kiwi Norge AS',
                            engagementtype: Ansettelsesform.Fast,
                            classification_input_source: 'jobtitle',
                            employerdescription:
                                '<p>KIWI minipris er en av landets mest ekspansive lavpriskjeder og omfatter over 670 butikker. I 2019 forventer vi en samlet omsetning på 38,4 milliarder kroner. Kjedekonseptet er faste, lave priser på alle varer og en kostnadseffektiv drift. KIWI minipris er med i NorgesGruppen som er Norges største dagligvaregruppering.</p>\n',
                            sector: 'Privat',
                            sourceupdated: '2019-12-11T13:41:00.000Z',
                            applicationurl:
                                'https://kiwi.no/Informasjon/Ledigestillinger1/Apply/?rmpage=job&rmjob=5156&ref=https://www.finn.no',
                            applicationdue: '2020-05-30T10:00:00.000Z',
                            extent: Omfang.Heltid,
                            occupation: 'Butikksjef',
                            logomain:
                                'https://images.finncdn.no/mmo/logo/object/37451304/00-kiwi-minipris-logo.png',
                            externalref: 5156,
                            logolisting:
                                'https://images.finncdn.no/mmo/logo/result/37451304/iad_573601655058443411900-kiwi-minipris-logo_mediumlarge.png',
                            employerhomepage: 'http://www.kiwi.no',
                            searchtags: [
                                { label: 'Butikksjef', score: 0.9304218 },
                                { label: 'Butikksjef (supermarked)', score: 0.37218642 },
                                { label: 'Kjedesjef', score: 0.1827526 },
                                { label: 'Product Sales Manager', score: 0.1827526 },
                            ],
                            employer: 'KIWI Råbekken',
                            industry: 'Butikk og varehandel',
                            adtext:
                                '<p><strong>Bli en del av det grønne vinnerlaget!</strong></p>\n<p>KIWI Råbekken søker etter butikksjef</p>\n<p>Er du typen som skaper entusiasme og resultater? Trigges du av fornøyde kunder og medarbeidere? Har du en god porsjon konkurranseinstinkt og stå-på-vilje ? Da er kanskje denne jobben noe for deg.</p>\n<p>Gjennom årene har KIWI vært den soleklare vekstvinneren i det norsk dagligvaremarkedet. En leder i KIWI ser hver enkelt medarbeider, og hver enkelt kunde. Hos oss er det nemlig kunden som er sjefen, og målet er at hver enkelt KIWI-butikk skal være best i sitt område. Hver eneste medarbeider er viktig i KIWI og gjennom å gjøre hverandre bedre skal vi vinne kundene.</p>\n<p>Butikksjefen på KIWI Råbekken har fått nye muligheter, og vi søker en etterfølger. Butikken omsetter for 43 millioner kroner årlig. Som butikksjef vil du ha ansvar for å motivere de 12 medarbeiderne i butikken, og bidra til at butikken fortsetter å levere gode handleopplevelser for kunden. Du vil ha det fulle og hele ansvaret for driften av butikken, inkludert personal-, økonomi- og resultatansvar.</p>\n<p><strong>Som søker må du ha:</strong></p>\n<ul><li>Ledererfaring som butikksjef eller assisterende butikksjef</li><li>Kremmerånd og oppnådd gode resultater tidligere</li><li>Plettfri vandel, blant annet for å få salgsbevilling på alkohol i butikk</li></ul>\n<p><strong>For å lykkes i KIWI, bør du:</strong></p>\n<ul><li>Evne å skape entusiasme og trivsel blant dine kolleger</li><li>Ha gjennomføringsevne, stor arbeidskapasitet og trives med en hektisk hverdag</li><li>Ha konkurranseinstinkt og vilje til å skape gode resultater</li><li>Være tydelig, strukturert og positiv i møte med medarbeidere</li><li>Trives med å være synlig overfor kunder, og sikre at de får service utover det de forventer</li></ul>\n<p><strong>Hva kan du forvente av oss?</strong></p>\n<ul><li>En sosial og trivelig arbeidsplass med masse hyggelige kolleger</li><li>Utfordrende og varierte arbeidsoppgaver</li><li>Grundig opplæring gjennom KIWIskolen og tett oppfølging fra vårt driftsapparat</li><li>En dynamisk og uformell organisasjon med kjappe og korte kommunikasjonslinjer</li><li>Konkurransedyktig lønn og bonusavtale</li><li>Spennende utviklingsmuligheter</li></ul>\n<p>*I KIWI mener vi at mangfold beriker, og våre medarbeidere skal speile befolkningen. Vi oppfordrer alle kvalifiserte kandidater til å søke, uavhengig av kjønn, alder, nasjonal eller etnisk bakgrunn.</p>\n<p>**Vi gjør oppmerksom på at alle søknader må sendes inn via søknadskjema tilknyttet annonsen, samt at det meste av kommunikasjonen vedrørende stillingen vil skje per e-post.</p>\n',
                            location: 'Rolvsøy',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: 'bf724aa1-0459-4514-ae6d-6411688223d6',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Produksjonsmedarbeidere',
                        uuid: 'bf724aa1-0459-4514-ae6d-6411688223d6',
                        annonsenr: '123456',
                        status: 'INACTIVE',
                        privacy: 'SHOW_ALL',
                        published: '2019-12-20T05:30:02.278972',
                        expires: '2020-01-10T23:59:59',
                        created: '2019-12-19T05:31:08.708453',
                        updated: '2020-01-11T01:31:21.002137',
                        employer: {
                            name: 'PLA-MEK AS',
                            publicName: 'PLA-MEK AS',
                            orgnr: '972884243',
                            parentOrgnr: '964837090',
                            orgform: 'BEDR',
                        },
                        categories: [],
                        source: 'POLARIS',
                        medium: 'POLARIS',
                        businessName: 'Pla-Mek',
                        locations: [
                            {
                                address: 'Naustvegen 12 ',
                                postalCode: '6230',
                                county: 'MØRE OG ROMSDAL',
                                municipal: 'SYKKYLVEN',
                                latitue: '62.4087978',
                                longitude: '6.55004570000006',
                            },
                        ],
                        reference: '16323',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'www.smp.no/stillingledig/#/landingPage/landingpage/16323',
                            positioncount: 2,
                            author: 'Sunnmørsposten',
                            sourcecreated: '2019-12-18T09:35:02.617',
                            engagementtype: Ansettelsesform.Fast,
                            classification_input_source: 'title',
                            employerdescription:
                                '<p>Pla-Mek AS ble etablert i 1992 og har siden starten hatt en kontinuerlig utvikling til å bli en av landets ledende sprøytestøpere av plast. Markedet er B2B der kunden er eier av produktet hvor vi bidrar med produkt- og produksjonsutvikling. Produktene er teknisk avanserte og blir produsert i en helautomatisk prosess med mye robotisering. Bedriften er lokalisert i Sykkylven.</p><p>Du kan lese mer <a href="https://www.pla-mek.no/" rel="nofollow">her</a></p>\n',
                            sector: 'Privat',
                            sourceupdated: '2019-12-19T08:12:14.740',
                            applicationurl:
                                'https://www.finn.no/job/fulltime/ad.html?finnkode=165663619',
                            applicationdue: '28.02.2020',
                            extent: Omfang.Heltid,
                            logomain:
                                'media.webassistenten.no/api/image/get/jobs/75706C6F6164735C336131323131623065613135633138612E6A7067',
                            starttime: 'Etter avtale',
                            searchtags: [
                                { label: 'Produksjonsmedarbeider', score: 0.95641875 },
                                { label: 'Fabrikkarbeider', score: 0.43986267 },
                                { label: 'Industrisyer', score: 0.2884207 },
                            ],
                            employer: 'Pla-Mek',
                            industry: 'Industri / Produksjon;Metallurgisk industri / Metallvarer',
                            adtext:
                                '<p>Pla-Mek sine maskiner har stor automasjonsgrad. Jobben som produksjonsmedarbeider innbefatter arbeidsoppgaver som:<br />* Omstilling maskiner/formverktøy<br />* Optimalisere prosessparameter på maskiner<br />* Håndtering råstoff<br />* Programmering av robot/automasjon<br />* Produktkontroll<br />* Systematisk kvalitetsarbeid<br />* Reparasjon/vedlikeholdsarbeid maskiner/automasjon</p><p> ØNSKEDE KVALIFIKASJONER OG EGENSKAPER<br />* Fagbrev/utdannelse som industri-automasjon/mekaniker<br />* Kunnskap og erfaring fra produksjon<br />* Interesse og legning for kontinuerlige forbedringsprosesser</p><p>Vi ser etter deg som er ansvarsbevisst og selvstendig. Du må like å arbeide i team og være løsningsorientert.<br /></p><p>VI KAN TILBY<br />* Spennende og utfordrende stilling i en automatisert produksjon<br />* Godt arbeidsmiljø i en fleksibel bedrift der du kan påvirke din egen utvikling<br />* God opplæring og oppfølging<br />* Spennende kunder og produkter<br />* Lønn etter avtale</p><p>Spørsmål om stillingen kan rettes til fabrikksjef Bjarne Olav Velle, tlf. 984 83 000.<br /></p><p>Attester vil bli etterspurt ved behov.<br /></p><p>Søknadsfrist: 10.01.2020.<br /></p>\n',
                            location: 'Sykkylven',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: '260b0cd7-d7d0-4a90-a8ea-57e9ced586b1',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Autorisert regnskapsfører eller regnskapsfører med erfaring søkes',
                        uuid: '260b0cd7-d7d0-4a90-a8ea-57e9ced586b1',
                        annonsenr: '123456',
                        status: 'INACTIVE',
                        privacy: 'SHOW_ALL',
                        published: '2019-11-30T07:04:00.878136',
                        expires: '2020-01-10T17:48:00',
                        created: '2019-05-24T07:32:16.112',
                        updated: '2020-01-11T01:31:12.871373',
                        employer: {
                            name: 'EKSAKT ØKONOMI AS',
                            publicName: 'EKSAKT ØKONOMI AS',
                            orgnr: '923598847',
                            parentOrgnr: '923564772',
                            orgform: 'BEDR',
                        },
                        categories: [
                            {
                                styrkCode: '3313.06',
                                name: 'Konsulent (økonomi - privat virksomhet)',
                            },
                        ],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'Eksakt Økonomi AS',
                        locations: [
                            {
                                address: 'Plassen 1',
                                postalCode: '8006',
                                county: 'NORDLAND',
                                municipal: 'BODØ',
                                latitue: '67.28667449951172',
                                longitude: '14.398415565490723',
                            },
                        ],
                        reference: '148114513',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'https://www.finn.no/148114513',
                            classification_styrk08_score: 0.9556449,
                            address: 'Plassen 1,8006 Bodø',
                            jobtitle: 'Regnskapsfører',
                            author: 'Privat',
                            keywords:
                                'regnskapsbyrå,regnskapsfører,lønnsmedarbeider,årsoppgjør,elektronisk fremtid',
                            engagementtype: Ansettelsesform.Fast,
                            classification_input_source: 'occupation',
                            sector: 'Privat',
                            sourceupdated: '2019-11-29T17:48:00.000Z',
                            applicationurl:
                                'https://www.finn.no/recruitment/hired/frontend/applynow/input.action?adId=148114513',
                            applicationdue: Søknadsfrist.Snarest,
                            extent: Omfang.Heltid,
                            occupation: 'Økonomi og regnskap',
                            applicationemail: 'aleksander@eksaktokonomi.no',
                            externalref: 148114513,
                            searchtags: [
                                { label: 'Økonomiarbeider', score: 0.95508844 },
                                { label: 'Bokholderassistent', score: 0.12877588 },
                                { label: 'Controller', score: 0.04072808 },
                            ],
                            employer: 'Eksakt Økonomi AS',
                            industry: 'Økonomi og regnskap',
                            adtext:
                                '<p>Eksakt Økonomi AS er et spennende lite regnskapskontor i Bodø med pr i dag 4 ansatte. Vi søker en dyktig og positiv regnskapsfører som er åpen for nye utfordringer.</p>\n<p>Vårt firma skal utvikles videre. Faglige kvalifikasjoner som særlig vektlegges:</p>\n<p>-Autorisert regnskapsfører</p>\n<p>-Generelt faglig stødig, god regnskapforståelse</p>\n<ul><li>Sterk på lønnsarbeid og regelverk tilknyttet dette. Eventuelt har ambisjon om å bli det.</li></ul>\n<p>-God forståelse og interesse for IT, programvare, digitalisering</p>\n<p>Vi vurderer også søknader fra godt kvalifiserte ikke-autoriserte eller hvis du ligger an til å kunne løse ut autorisasjon innen kort tid.</p>\n<p>Hos oss får du ansvar for egen portefølje fra A til Å. Regnskapsførsel, lønnskjøring, avstemming, rapportering, årsoppgjør mv. Kjennskap til Visma Business / Visma Lønn / Poweroffice GO er en fordel. Mulighet for oppdragsansvar.</p>\n<p>Det gis opplæring og veiledning, samtidig som bedriften er avhengig av at du har egenskapene som gjør at du glir fort inn i arbeidsoppgavene, er strukturert og kan ta selvstendig ansvar. Du har godt humør og liker å stå på. God arbeidskapasitet. Skape gode relasjoner med kolleger og kunder.</p>\n<p>Stillingen er i utgangspunktet fulltid 100%. Tidspunkt for start avtales nærmere. Vi tar i mot søknader fortløpende, så ikke vent for lenge med å ta kontakt hvis du er rette person.</p>\n<p>Vi tilbyr konkurransedyktige betingelser. Sosiale goder er for eksempel tilgang til firmahytte, forskjellige sosiale aktiviteter. Sentrumsnære lokaler ved jernbanestasjonen med frie parkeringsforhold.</p>\n<p>Ta gjerne kontakt hvis du har noen spørsmål eller for en uforpliktende prat.</p>\n<p>Søknad med CV sendes på mail eller via finn.no.</p>\n',
                            location: 'Bodø',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: '754a1dd7-71d7-4521-bc69-34d8ed94cd20',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Talent for økonomi og hjerte for mennesker?',
                        uuid: '754a1dd7-71d7-4521-bc69-34d8ed94cd20',
                        annonsenr: '123456',
                        status: 'INACTIVE',
                        privacy: 'SHOW_ALL',
                        published: '2019-11-30T07:04:01.341778',
                        expires: '2020-01-10T22:59:00',
                        created: '2019-11-30T07:07:28.761932',
                        updated: '2020-01-11T01:31:16.839001',
                        employer: {
                            name: 'CLARION HOTEL & CONGRESS OSLO AIRPORT AS',
                            publicName: 'CLARION HOTEL & CONGRESS OSLO AIRPORT AS',
                            orgnr: '977313406',
                            parentOrgnr: '981048911',
                            orgform: 'BEDR',
                        },
                        categories: [{ styrkCode: '2412.12', name: 'Business controller' }],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'Clarion Hotel & Congress Oslo Airport',
                        locations: [
                            {
                                address: 'Hans Gaarders vei 60',
                                postalCode: '2060',
                                county: 'VIKEN',
                                municipal: 'ULLENSAKER',
                                latitue: '60.195377349853516',
                                longitude: '11.070162773132324',
                            },
                            {
                                address: 'Dikeveien 6',
                                postalCode: '1661',
                                county: 'VIKEN',
                                municipal: 'FREDRIKSTAD',
                                latitue: '59.24449920654297',
                                longitude: '10.98370361328125',
                            },
                        ],
                        reference: '164437229',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'https://www.finn.no/164437229',
                            classification_styrk08_score: 1.0,
                            address: 'Hans Gaarders vei 60,2060 Gardermoen',
                            jobtitle: 'Business Controller',
                            author: 'Loyalty People MANAGEMENT',
                            keywords: 'Controller,Regnskap,Lønn,Finans,Analyse,Rapportering',
                            engagementtype: Ansettelsesform.Fast,
                            classification_input_source: 'jobtitle',
                            employerdescription:
                                '<p>Clarion Hotel &amp; Congress Oslo Airport er Norges største konferansehotell og ligger sentralt til ved Oslo Airport Gardermoen. Hotellet har 432 rom og tilbyr over 45 fleksible møterom med en totalkapasitet på 8000 konferansedeltakere. Hotellet åpnet i august 2014 dørene til et nytt kongressenter, The Qube. Bygget har et netto etasjeareal på 13.000 kvadratmeter og brukes til messer og konferanser inntil 6000 personer.</p>\n<p>Comfort Hotell Runway ligger ved siden av Clarion Hotel og har 303 moderne dobbeltrom og en total konferansekapasitet på 732 deltakere fordelt på 15 møterom. Hotellene ligger kun åtte minutter unna Oslo Airport Gardermoen, noe som gjør det enkelt å samle deltagere fra hele verden. Nordic Choice er en hotellkjede med rundt 190 hoteller i Skandinavia, Finland og Baltikum. Nordic Choice Hotels har en årlig omsetning på over 13 milliarder kroner og har rundt 14 000 ansatte.</p>\n',
                            sector: 'Privat',
                            sourceupdated: '2019-11-29T16:01:00.000Z',
                            applicationurl:
                                'https://apply.recman.no/job_post.php?id=113835&path=finn',
                            extent: Omfang.Heltid,
                            logomain:
                                'https://images.finncdn.no/mmo/logo/object/790312945/iad_4921366773981909339loyalty_people-logo-management-pos.png',
                            externalref: 113835,
                            employerhomepage: 'https://www.nordicchoicehotels.no/',
                            starttime: 'Etter avtale',
                            searchtags: [
                                { label: 'Business Controller', score: 1.0 },
                                {
                                    label: 'Senior Business Controller - Divisjon',
                                    score: 0.22452071,
                                },
                                { label: 'Country Business Controller', score: 0.22452071 },
                                { label: 'Senior Business Controller', score: 0.22452071 },
                                { label: 'Junior Business Controller', score: 0.22452071 },
                            ],
                            employer: 'Clarion Hotel & Congress Oslo Airport',
                            industry: 'Hotell og overnatting',
                            adtext:
                                '<p><strong>Talent for økonomi og hjerte for mennesker?</strong></p>\n<p>Unik mulighet! Til en meget spennende stilling søker vi en engasjert og løsningsorientert Business Controller som brenner for både økonomi, teamwork og fornøyde gjester. I denne stillingen vil du fungere som en strategisk partner og operativ støttefunksjon for hotellets direktør og lederteam. Du vil gi veiledning med treffsikre analyser og rapporter, slik at vi sammen når våre målsettinger. Sentrale oppgaver vil være å drive &#34;business performance&#34;, som innebærer oppfølging av KPI&#96;er innenfor fokusområdene WeCare, gjest og vekst samt foreslå, implementere og følge opp effektiviseringstiltak. Videre vil du ha ansvar for kontroll og oppfølging av den finansielle styringsinformasjonen i henhold til target, forecast, strategi og den månedlige rapporteringen.</p>\n<p>I Nordic Choice vil du være med å påvirke utviklingen og kulturen gjennom den du er, og det arbeidet du utfører. Nordic Choice skal både være det beste stedet å jobbe, og det beste stedet å være gjest, fordi vi vet at dette henger sammen.</p>\n<p><strong>Tar du utfordringen?</strong><br />\nVi ser etter deg med høyere økonomisk utdannelse og relevant erfaring, gjerne fra hotell eller servicebransjen. Den rette personen liker å jobbe i et dynamisk miljø med et generøst mangfold av personligheter og ferdigheter. Det er avgjørende at du er god med mennesker, og viser entusiasme og stolthet i arbeidet du utfører.</p>\n<p><strong>Vi tilbyr deg:</strong></p>\n<ul><li>Karrieremulighet i Nordens råeste hotellkonsern</li><li>En variert og meningsfull jobbhverdag</li><li>En nøkkelrolle med store påvirkningsmuligheter</li><li>Konkurransedyktige betingelser</li><li>Personlig og faglig utvikling</li><li>Et fantastisk og fargerikt arbeidsmiljø med dedikerte kolleger</li></ul>\n<p><strong>Ønskede kvalifikasjoner og egenskaper:</strong></p>\n<ul><li>Relevant høyskoleutdannelse</li><li>3-5 års erfaring med bedriftsøkonomi, prognose, analyse og rapportering</li><li>Erfaring fra hotell eller servicebransjer er foretrukket</li><li>Høy muntlig og skriftlig kommunikasjonsevne</li><li>Serviceinnstilt, analytisk og grundig</li><li>Liker samarbeid med mennesker med ulik erfaring og bakgrunn</li><li>Opptatt av miljø, mangfold og et bærekraftig reiseliv</li><li>Har masse energi, mot og begeistring</li></ul>\n<p>Ønsker du ytterligere informasjon? Ta kontakt med rådgiver, Christian Westermark i Loyalty People. Alle henvendelser behandles konfidensielt, om ønskelig også overfor oppdragsgiver. Vi oppfordrer til å søke omgående.</p>\n<p>Tlf: 48 28 39 72 / christian.westermark&#64;loyaltypeople.no</p>\n<p><strong>Velkommen med din søknad!</strong></p>\n',
                            location: 'Gardermoen',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: 'ce20cc95-4c09-48cd-82cf-84a4e4a51008',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Elektriker',
                        uuid: 'ce20cc95-4c09-48cd-82cf-84a4e4a51008',
                        annonsenr: '123456',
                        status: 'INACTIVE',
                        privacy: 'SHOW_ALL',
                        published: '2019-11-30T07:04:01.344606',
                        expires: '2020-01-10T22:59:00',
                        created: '2019-11-30T07:07:28.785202',
                        updated: '2020-01-11T01:31:16.887642',
                        employer: {
                            name: 'TOPTEMP AS AVD OSLO',
                            publicName: 'TOPTEMP AS AVD OSLO',
                            orgnr: '987587806',
                            parentOrgnr: '987560274',
                            orgform: 'BEDR',
                        },
                        categories: [{ styrkCode: '7411.01', name: 'Elektriker' }],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'Toptemp AS',
                        locations: [
                            {
                                address: 'Strandgata 19',
                                postalCode: '0152',
                                county: 'OSLO',
                                municipal: 'OSLO',
                                latitue: '59.91029357910156',
                                longitude: '10.749537467956543',
                            },
                        ],
                        reference: '164433628',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            classification_styrk08_score: 0.5732685,
                            positioncount: 5,
                            author: 'Top Temp AS',
                            keywords: 'elektriker,montør,installasjon,oslo,elektro',
                            engagementtype: Ansettelsesform.Prosjekt,
                            classification_input_source: 'jobtitle',
                            sector: 'Privat',
                            sourceupdated: '2019-11-29T15:06:00.000Z',
                            applicationurl: 'https://www.toptemp.no/ledig-stilling/?id=2875&o=88',
                            extent: Omfang.Heltid,
                            occupation: 'Håndverker',
                            externalref: 8576,
                            logolisting:
                                'https://images.finncdn.no/mmo/logo/result/233328108/iad_1134199020174270790logo_horisontal_black__1_.png',
                            starttime: 'Snarest',
                            searchtags: [
                                { label: 'Elektriker', score: 0.5654293 },
                                { label: 'Elektriker - sikkerhetsmontør', score: 0.12513657 },
                                { label: 'Cable Railway Rigger', score: 0.073123835 },
                                { label: 'Automatiseringsmontør', score: 0.073123835 },
                                { label: 'High-voltage electric technician', score: 0.073123835 },
                            ],
                            employer: 'Toptemp AS',
                            industry: 'Bygg og anlegg;Håndverkstjenester;Elektronikk',
                            adtext:
                                '<p>Vi trenger erfarne elektrikere til et langvarig prosjekt i Oslo innen nybygg av leiligheter. Du vil jobbe for et kjent kunde, og vi har troen på at din arbeidsmoral og engasjement vil bli en stor ressurs der.</p>\n<p>Vi ser for oss at du har noen års erfaring, er fleksibel, arbeidssom, selvstendig og har teknisk erfaring. Arbeidstidene er fleksible hvor du kan jobbe mandag-fredag eller mandag-torsdag.</p>\n<p>Vi fikser bolig, samt arbeidsklær og verktøy. Bor du i Oslo fra før, og har egen bolig, blir du kompensert i form av boligtillegg. Du trenger med andre ord bare å møte opp på arbeidsplassen med ditt positive sinn, klar til å levere gode resultater. Resten fikser vi.</p>\n<p>Høres dette ut som deg? SØK DA VEL! :)</p>\n<p><strong>Kvalifikasjoner:</strong></p>\n<ul><li>Fagbrev som elektriker Gr.L/DSB lavspenning<br />\n• Erfaring etter fagbrev, helst fra montasje<br />\n• Snakker et skandinavisk språk flytende<br />\n• Er selvgående men jobber godt i team for å oppnå gode resultater<br />\n• Liker nye utfordringer og kan sette seg raskt inn i nye arbeidsoppgaver</li></ul>\n<p><strong>Vi tilbyr:</strong></p>\n<ul><li>Gratis bolig/boligtillegg, arbeidsklær og verktøy</li><li>Gode lønnsvilkår</li><li>Nye kollegaer som snakker skandinavisk</li><li>Prosjekter som varierer i kompleksitet, størrelse og varighet</li><li>Karrieremuligheter som f.eks. bas, mellombas og kurs</li></ul>\n<h3>Om Toptemp</h3>\n<p><strong>Er du klar for det neste steget i karrieren din? Hvert år hjelper vi tusenvis av personer inn i riktig jobb.</strong></p>\n<p>Vi er her for å hjelpe deg, enten du er jobbsøker på jakt etter ditt neste oppdrag, prosjekt eller selveste drømmejobben.</p>\n<p>Siden 1990 har vi funnet og formidlet talenter over hele landet -- og internasjonalt. Vi bemanner og rekrutterer for våre kunder innen de fleste bransjer og fagområder som engineering, elektro, offshore, finans, økonomi og regnskap, HR og personal, lager og logistikk, handel og kontor, hotell og restaurant, salg og markedsføring, IT og teknologi.</p>\n',
                            location: 'Oslo',
                            sourceurl: 'https://www.finn.no/164433628',
                            address: 'Strandgata 19,0152 Oslo',
                            jobtitle: 'Elektriker og vil jobbe sentralt i Oslo?',
                            applicationdue: Søknadsfrist.Snarest,
                            logomain:
                                'https://images.finncdn.no/mmo/logo/object/233328108/iad_3302198555497126925logo_horisontal_black__1_.png',
                            applicationlabel: 'Stilling2875',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: 'dd88443c-4610-4cdf-ac35-55e456aced02',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Platearbeider i stålindustri',
                        uuid: 'dd88443c-4610-4cdf-ac35-55e456aced02',
                        annonsenr: '123456',
                        status: 'STOPPED',
                        privacy: 'SHOW_ALL',
                        published: '2019-12-07T07:04:13.918246',
                        expires: '2020-01-17T22:59:00',
                        created: '2019-12-07T07:07:51.752778',
                        updated: '2020-01-11T07:10:04.78456',
                        employer: {
                            name: 'BACKUP BYGGPERSONELL AS AVD TRONDHEIM',
                            publicName: 'BACKUP BYGGPERSONELL AS AVD TRONDHEIM',
                            orgnr: '920720617',
                            parentOrgnr: '997315057',
                            orgform: 'BEDR',
                        },
                        categories: [{ styrkCode: '7214.02', name: 'Platearbeider' }],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'BackUp Byggpersonell AS',
                        locations: [
                            {
                                address: null,
                                postalCode: '7038',
                                county: 'TRØNDELAG',
                                municipal: 'TRONDHEIM',
                                latitue: '63.38679885864258',
                                longitude: '10.400192260742188',
                            },
                        ],
                        reference: '164953207',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            classification_styrk08_score: 1.0,
                            positioncount: 2,
                            author: 'BackUp Byggpersonell AS',
                            keywords: 'Platearbeider,Spawacz,Stål,Sveiser',
                            engagementtype: Ansettelsesform.Vikariat,
                            classification_input_source: 'jobtitle',
                            sector: 'Privat',
                            sourceupdated: '2019-12-06T11:54:00.000Z',
                            applicationurl:
                                'https://secure.webtemp.no/WebtempCVPortal/default.aspx?k=23&id_utleie=3010396',
                            extent: Omfang.Heltid,
                            occupation: 'Produksjon',
                            externalref: 20007727601,
                            logolisting:
                                'https://images.finncdn.no/mmo/logo/logo/141838280/20190424/305a5977-eed6-4a6c-bd71-e816347ad25d',
                            starttime: 'Snarest',
                            searchtags: [
                                { label: 'Platearbeider', score: 1.0 },
                                { label: 'Montør', score: 0.32391462 },
                                { label: 'Stålmontør', score: 0.11513306 },
                            ],
                            employer: 'BackUp Byggpersonell AS',
                            industry: 'Bygg og anlegg',
                            adtext:
                                '<p>Til en av våre kunder søker vi platearbeider/ montører med sveiseerfaring for lengre oppdrag.</p>\n<h2>Ønskede kvalifikasjoner</h2>\n<ul><li>Platearbeider med sveise-erfaring pinne og rørtråd</li><li>Sveising med MIG, TIG, PVC</li><li>Norsk-/engelsktalende</li></ul>\n<h2>Personlige egenskaper</h2>\n<ul><li>Nøyaktig</li><li>Arbeidsom</li><li>Løsningsorientert</li><li>Pålitelig og selvstendig</li></ul>\n<h2>Vi tilbyr</h2>\n<ul><li>Attraktiv lønn</li><li>Langt oppdrag</li><li>Godt arbeidsmiljø</li></ul>\n<p>Følg linken og søk på stillingen. Har du noen spørsmål om stillingen, gjerne ta kontakt med Agnieszka tlf: &#43;47 925 220 75 eller e-mail az&#64;backup-bygg.no</p>\n',
                            location: 'Trondheim',
                            sourceurl: 'https://www.finn.no/164953207',
                            address: 7038,
                            jobtitle: 'Platearbeider/ montører med sveise erfaring',
                            employerdescription:
                                '<p>BackUp Gruppen har siden 1997 vært en totalleverandør av rekrutterings- og bemanningsløsninger.</p>\n<p>BackUp Byggpersonell er en spesialistavdeling i BackUp Gruppen som leverer kvalifisert bemanning til bygg &amp;anlegg og industrisektoren. Solid fagkompetanse hos våre konsulenter sikrer produktive og fleksible bemanningsløsninger for våre kunder.<br />\nVi betjener hele landet gjennom våre avdelinger i Stor-Oslo, Østfold, Vestfold, Sørlandet, Rogaland, Midt-Norge og Nord-Norge.</p>\n',
                            applicationdue: Søknadsfrist.Snarest,
                            logomain:
                                'https://images.finncdn.no/mmo/logo/logo/141838280/20190424/80bec4f1-dd3b-4e85-9acd-5bd266cf99d4',
                            applicationlabel: 77276,
                            employerhomepage: 'http://www.backup-bygg.no',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: '1af6a869-cc8d-46d3-85eb-d816625c473b',
                _score: 1.0,
                _source: {
                    stilling: {
                        title:
                            'Vil du være med å bidra til vekst & lønnsomhet i en moderne bedrift som krever konstant fokus på trender og evne til omstilling ?',
                        uuid: '1af6a869-cc8d-46d3-85eb-d816625c473b',
                        annonsenr: '123456',
                        status: 'INACTIVE',
                        privacy: 'SHOW_ALL',
                        published: '2019-12-03T07:04:22.275608',
                        expires: '2020-01-10T22:59:00',
                        created: '2019-12-03T07:08:12.373175',
                        updated: '2020-01-11T01:31:16.990061',
                        employer: {
                            name: 'JENSEN & CO AS AVD LILLESTRØM',
                            publicName: 'JENSEN & CO AS AVD LILLESTRØM',
                            orgnr: '819056722',
                            parentOrgnr: '913092724',
                            orgform: 'BEDR',
                        },
                        categories: [{ styrkCode: '1211.02', name: 'Økonomidirektør' }],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'Jensen & Co',
                        locations: [
                            {
                                address: 'Tærudgata 16',
                                postalCode: '2004',
                                county: 'VIKEN',
                                municipal: 'LILLESTRØM',
                                latitue: '59.951656341552734',
                                longitude: '11.047581672668457',
                            },
                        ],
                        reference: '164641190',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'https://www.finn.no/164641190',
                            classification_styrk08_score: 1.0,
                            address: 'Tærudgata 16,2004 Lillestrøm',
                            jobtitle: 'CFO',
                            author: 'Bønes Virik AS',
                            keywords:
                                'Finans,Regnskap,Forretningsutvikling,Økonomistyring,Strategi',
                            engagementtype: Ansettelsesform.Fast,
                            classification_input_source: 'jobtitle',
                            employerdescription:
                                '<p>&#34;Vi motiveres av å tilføre mer praktiske, bedre og sunnere matvarer som norske forbrukere tar inn i sin hverdag. Når det kommer til stykket er det matglede det handler om og betydningen av fellesskapet som måltidet representerer. Vi vil være der. På ditt bord. Med glede! &#34;<br />\nJensen &amp; Co er en fremtidsrettet partner for dagligvarehandelen &amp; våre leverandører med fokus på salg - som vi oppnår gjennom innsikt og forståelse av norske forhold. Vi er en ambisiøs partner med fokus på vekst innen fremvoksende kategorier, serveringsmarkedet og satsning på norske aktører. Vi er spesialister innen kategorier som fri for, plantebasert, frokost, tørt brød &amp; barnemat. Vi er en moderne bedrift i en bransje som krever konstant fokus på trender og evne til omstilling. Hos oss vil du føle endringer i våre matvaner på kroppen &amp; du vil være en del av et team som stadig utfordrer for å oppnå vekst!</p>\n',
                            sector: 'Privat',
                            sourceupdated: '2019-12-02T10:24:00.000Z',
                            applicationurl:
                                'https://apply.recman.no/job_post.php?id=113768&path=finn',
                            applicationdue: Søknadsfrist.Snarest,
                            extent: Omfang.Heltid,
                            occupation: 'Ledelse;Økonomi og regnskap',
                            logomain:
                                'https://images.finncdn.no/mmo/logo/logo/96879240/20190906/b9799d51-7140-4d44-912c-e449de639975',
                            externalref: 113768,
                            logolisting:
                                'https://images.finncdn.no/mmo/logo/logo/96879240/20190906/5906b3d4-d2d0-44e5-91a3-8530a523d1dc',
                            employerhomepage: 'https://jensenco.no',
                            searchtags: [
                                { label: 'Finansdirektør', score: 1.0 },
                                { label: 'Billing Manager', score: 0.42062092 },
                                { label: 'Chief Executive Officer', score: 0.29066187 },
                                { label: 'Ligningssjef', score: 0.28506464 },
                                { label: 'Administrasjonssjef', score: 0.28506464 },
                            ],
                            employer: 'Jensen & Co',
                            industry:
                                'Matvareproduksjon og -industri;Annet;Grossisthandel import/eksport',
                            adtext:
                                '<p>I rollen som CFO har du en variert stilling med særskilt ansvar for å bidra til vekst &amp; lønnsomhet. Du er en aktiv bidragsyter til utviklingen av bedriften både strategisk, strukturelt og operativt. I rollen er du en svært viktig støttespiller og samarbeidspartner til CEO med god innsikt i hele virksomheten. Stillingen er en del av ledergruppen og din stilling deltar ved styremøter. Fagområdene økonomi- og regnskapsfunksjon, Legal, Finans, valuta, IT, HR &amp; Miljø ligger innunder stillingen. Avdelingen er selskapets interne rådgivere innen sine fagområder og skal være pådriver for vekst- og lønnsomhets forbedringer.</p>\n<p>Om ansvarsfordeling<br />\nStedfortreder til CFO er Business Controller <strong>I</strong> CFO er stedfortreder til CEO <strong>I</strong> CFO har i dag ansvar for 3 stillinger som rapporterer inn til seg: Business Controller, Regnskapsansvarlig &amp; IT-ansvarlig.</p>\n<p><strong>Arbeidsoppgaver</strong><br />\nDu har en variert hverdag som består av både strategiske &amp; operative oppgaver</p>\n<ul><li>Strategi og virksomhetsutvikling; være en proaktiv person og pådriver innen forretningsutvikling og strategiarbeid, herunder initiativ til å løfte topplinje og bunnlinje, samt å være en aktiv sparringspartner for CEO</li><li>Videreutvikle og drifte økonomistyring i Jensen &amp; Co, herunder produksjon og kvalitetssikring av både selskaps- og konsernregnskap, budsjettering, KPI og likviditetsstyring, prognoser, ukes- og månedsrapportering</li><li>Utvikling av styringsmodeller, analysemetodikk, rapporteringsverktøy og nøkkeltall, samt implementere og iverksette tiltak basert på disse med fokus på lønnsomhet og ytterligere forbedringer</li><li>Finansiering og valutasikring kontakt med eksterne institusjoner som banker, revisor etc.</li><li>Digitaliseringsprosjekter</li><li>Legal compliance, herunder leverandørkontrakter og ansettelsesavtaler</li><li>Generell operasjonell støtte, samt bidra til økt økonomiforståelse blant ledere og ansatte for øvrig</li></ul>\n<p><strong>Om deg</strong><br />\nØkonomisk utdannelse på masternivå I minimum &#43;5 års relevant erfaring</p>\n<p>Interesse for Jensen &amp; Co sine verdier:<br />\nTroverdig <strong>I</strong> Personlig <strong>I</strong> Løsningsorientert <strong>I</strong> Nyskapende</p>\n<p>Du er forretningsorientert med en operativ arbeidsstil som evner å skape retning. Du liker å utfordre eksisterende praksis på en måte som skaper trygghet, takhøyde &amp; gjensidig forståelse. Samtidig er du handlekraftig og forhandlingsvant og en god lagspiller. Du er analytisk, strukturert &amp; beslutningsdyktig.</p>\n<p>Vi tilbyr en allsidig og spennende stilling, hvor du er en viktig del av veksten &amp; fremtidsmulighetene. Du vil være en del av et miljø som jobber for en bedre mathverdag!</p>\n<p>Ønsker du ytterligere informasjon, er du velkommen til å ta kontakt med vår rekrutteringspartner Bønes Virik ved Jostein Hjellegjerde (91 12 12 17) eller Christine Finset (92 01 07 31)</p>\n<p><strong>Søknadsfrist</strong> , snarest.</p>\n',
                            location: 'Lillestrøm',
                        },
                    },
                    stillingsinfo: null,
                },
            },
            {
                _index: 'stilling_7',
                _type: '_doc',
                _id: '4cf84244-2ef5-4975-8c0a-50ce6944d610',
                _score: 1.0,
                _source: {
                    stilling: {
                        title: 'Erfaring fra sosiale medier annonsering?',
                        uuid: '4cf84244-2ef5-4975-8c0a-50ce6944d610',
                        annonsenr: '123456',
                        status: 'STOPPED',
                        privacy: 'SHOW_ALL',
                        published: '2019-12-10T07:04:05.775902',
                        expires: '2020-01-20T12:05:00',
                        created: '2019-05-09T07:18:20.315',
                        updated: '2020-01-11T07:10:05.244911',
                        employer: {
                            name: 'OPTIMAL NORGE AS',
                            publicName: 'OPTIMAL NORGE AS',
                            orgnr: '994853058',
                            parentOrgnr: '994824066',
                            orgform: 'BEDR',
                        },
                        categories: [{ styrkCode: '2431.01', name: 'Markedsføringskonsulent' }],
                        source: 'FINN',
                        medium: 'FINN',
                        businessName: 'Optimal Norge AS',
                        locations: [
                            {
                                address: 'RYENSVINGEN 3',
                                postalCode: '0680',
                                county: 'OSLO',
                                municipal: 'OSLO',
                                latitue: '59.89344787597656',
                                longitude: '10.804930686950684',
                            },
                        ],
                        reference: '146969185',
                        administration: {
                            status: 'RECEIVED',
                            remarks: [],
                            comments: '',
                            reportee: '',
                            navIdent: '',
                        },
                        properties: {
                            sourceurl: 'https://www.finn.no/146969185',
                            classification_styrk08_score: 0.9973858,
                            address: 'RYENSVINGEN 3,0680 Oslo',
                            jobtitle: 'Social Media Manager',
                            author: 'Optimal Norge AS',
                            keywords: 'senior,Markedsføring,Sosiale medier,Facebook,SoMe',
                            engagementtype: Ansettelsesform.Fast,
                            classification_input_source: 'occupation',
                            employerdescription:
                                '<p>Optimal Norge AS er et mediebyrå i vekst. Vi jobber med store kjente merkenavn og bedrifter i alle bransjer.</p>\n<p>Optimal Norge AS ble stiftet i november 2009 av fire engasjerte gründere med lang fartstid fra mediebransjen. Vi lever av å gjøre kundene våre gode på nett.</p>\n<p>Vårt hovedmål er å formidle de mest kvalitative besøkende til kundens nettside ved bruk av riktig annonsering. Målet er å formidle relevante kunder som søker på deres varer og tjenester, og er klar til å betale for det.</p>\n<p>Vi har mange års erfaring innenfor performance marketing og sitter på en unik kompetanse for å kunne bistå våre kunder med å ta de rette beslutningene.</p>\n',
                            sector: 'Privat',
                            sourceupdated: '2019-12-09T12:05:00.000Z',
                            applicationurl:
                                'https://www.finn.no/recruitment/hired/frontend/applynow/input.action?adId=146969185',
                            applicationdue: Søknadsfrist.Snarest,
                            extent: Omfang.Heltid,
                            occupation: 'Markedsfører',
                            applicationemail: 'frode@optimalnorge.no',
                            externalref: 146969185,
                            employerhomepage: 'https://www.optimalnorge.no',
                            searchtags: [
                                { label: 'Markedsføringskonsulent', score: 0.9895892 },
                                { label: 'Content marketer', score: 0.29269433 },
                                { label: 'Grafiker førtrykk', score: 0.19619286 },
                                { label: 'Nettredaktør', score: 0.1223919 },
                                { label: 'Desktop Publisher', score: 0.10111935 },
                            ],
                            employer: 'Optimal Norge AS',
                            industry:
                                'Internettbaserte tjenester;Markedsføring og annonsering;Medie- og innholdsproduksjon',
                            adtext:
                                '<p>Optimal Norge ønsker å ansette en rådgiver til sosiale medier-avdeling. Her møter du varierte og spennende arbeidsoppgaver. Vi er et byrå i vekst og mulighetene er store for riktig person. Kanskje det er deg vi leter etter?</p>\n<p><strong>Arbeidsoppgaver</strong></p>\n<p>Arbeide daglig mot å realisere våre mål gjennom sosiale medier for våre kunder.</p>\n<p>Utvikle kreative ideer for å forbedre våre kontoer og teste nye funksjoner</p>\n<p>Samarbeide med kolleger for å finne de beste mulighetene for våre markedsbudsjett</p>\n<p><strong>Kvalifikasjoner</strong></p>\n<ul><li>Relevant høyere utdannelse innenfor markedsføring (relevant erfaring kan kompensere for utdannelse)</li><li>Du har minimum 2 års erfaring med digital markedsføring i et byrå</li><li>Du har ledet kampanjer i stor skala i sosiale medier</li><li>Erfaring med Google Analytics og Google Tag Manager</li><li>Du snakker flytende norsk og engelsk, det er en fordel om du kan andre språk</li><li>Du utmerker deg med dine skriftlige ferdigheter</li><li>God kunnskap i Excel</li><li>Det er en fordel om du har erfaring med ulike CMSer</li><li>Det er en fordel om du har erfaring med bilde eller videoredigering.</li></ul>\n<p>Du blir en del av annonseteamet på 4 kloke markedsførere og har fullt ansvar for kampanjestyringen for dine egne kunder.</p>\n<p><strong>Du har evnen til å</strong></p>\n<ul><li>Se hvilke tiltak som er mest effektive for kunden</li><li>Analysere resultater fortløpende</li><li>Prioritere tiltak etter viktighet</li><li>Jobbe strukturert og nøyaktig</li><li>Tilpasse dine arbeidsmåter etter kundens behov</li><li>Finne nye ressurser og teknikker for å forenkle eller forbedre arbeidshverdagen</li><li>Holde deg oppdatert på nyheter innen fagfeltet</li></ul>\n<p><strong>Vi kan tilby</strong></p>\n<p>• Konkurransedyktige betingelser</p>\n<p>• Erfarne, trivelige, sosiale og kompetente kolleger</p>\n<p>• En spennende hverdag hos et byrå i vekst</p>\n<p>• Mulighet for faglig og personlig utvikling</p>\n<p>• Nye og flotte lokaler på Ryen, med parkeringsplasser og god tilgang til kollektivtrafikk</p>\n<p><strong>En faglig sterk og sulten gjeng</strong></p>\n<p>På en arbeidsplass finnes det som regel svært mange ulike mennesker, og Optimal Norge er intet unntak. Felles for samtlige hos oss er at vi har en kjærlighet for faget, og en drivkraft som gjør at vi stadig utvikler oss og blir bedre hver dag. Vi diskuterer, utfordrer, hjelper og stiller opp for hverandre. Her er det mye kompetanse samlet under ett tak, noe alle har glede av -- spesielt våre kunder.</p>\n<p><strong>Trivsel og karriereutvikling</strong></p>\n<p>Vi opererer med flat struktur og det er faktisk hyggelig å ha lunsj med sjefen. Arbeidsdagen er stappfull av spennende utfordringer og vi legger til rette for at man skal fortsette å utvikle seg. Vi setter trivsel høyt -- alle skal glede seg til å komme på jobb, til og med på mandager. Smilet og latteren sitter alltid løst i både faglige og sosiale sammenhenger.</p>\n<p>Med så mange kreative hoder under samme tak, arrangeres det mye gøy i løpet av et år. Årlige turer og sosiale samlinger er langt ifra mangelvare hos oss, og hardt arbeid belønnes alltid! Lokalene er flotte og gjør det enkelt å koble av med en runde shuffleboard eller bordtennis mellom slagene.</p>\n<p><strong>Høres dette ut som noe for deg? Send søknad og CV da vel!</strong></p>\n',
                            location: 'Oslo',
                        },
                    },
                    stillingsinfo: null,
                },
            },
        ],
    },
    aggregations: {
        globalAggregering: {
            faner: {
                buckets: {
                    alle: {
                        doc_count: 282,
                    },
                    annonsetekst: {
                        doc_count: 277,
                    },
                    annonsetittel: {
                        doc_count: 87,
                    },
                    arbeidsgiver: {
                        doc_count: 52,
                    },
                },
            },
        },
    },
};
